version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo:5
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=clean-node-api
    volumes:
      - ./data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"
  api:
    container_name: clean-node-api
    build: .
    image: clean-node-api
    restart: always
    command: npm run start
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
    ports:
      - "5050:5050"
    links:
      - mongo