version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo:5
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=clean-node-api
    volumes:
      - ./data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"
  api:
    container_name: clean-node-api
    image: node:16
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --omit=dev && npm run debug"
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo